import Vue from "vue";
import iconfont from "./iconfont";
import FFilter from "./FFilter";
import FLayoutPanel from "./layout/FLayoutPanel";
import TwoV from "./layout/FLayoutPanel/TowVertical";
import XWrapper from "./xWrapper";
import iconButton from "./iconButton";
import notFind from "./notFind";
import treeSelect from "./treeSelect";
import mapPosition from "./mapPosition";
import mapArea from "./mapArea";
import tableSelect from "./tableSelect";
import FButtonTab from "./layout/FButtomTab";
import UploadPic from "./uploadPic";
import xColumn from "./xColumn";
import RoutePanel from "./routePanel";
import filterHead from "./filterHead";
import building from "@/views/building";
import FSpread from "./FSpread";
import "@/components/v-table/themes/gray/easyui.css";
import "@/components/v-table/themes/vue.css";
import EasyUI from "@/components/v-table";
import uploadFile from './uploadFile'
// import FTable from "./FTable";

Vue.use(EasyUI);
Vue.component("FFilter", FFilter);
Vue.component("Iconfont", iconfont);
Vue.component("FLayoutPanel", FLayoutPanel);
Vue.component("TwoH", FLayoutPanel);
Vue.component("TwoV", TwoV);
Vue.component("XWrapper", XWrapper);
Vue.component("IconButton", iconButton);
Vue.component("notFind", notFind);
Vue.component("treeSelect", treeSelect);
Vue.component("mapPosition", mapPosition);
Vue.component("tableSelect", tableSelect);
Vue.component("FButtonTab", FButtonTab);
Vue.component("UploadPic", UploadPic);
Vue.component("xColumn", xColumn);
Vue.component("RoutePanel", RoutePanel);
Vue.component("filterHead", filterHead);
Vue.component("mapArea", mapArea);
Vue.component("building", building);
Vue.component("FSpread", FSpread);
Vue.component("uploadFile", uploadFile);
