import ht from "ffcode-ht";
import "ffcode-ht/plugins/portal";
import "ffcode-ht/plugins/rulerframe";
import "ffcode-ht/plugins/vector";
import "ffcode-ht/plugins/ui-framework";
import "ffcode-ht/plugins/cssanimation";
import "ffcode-ht/plugins/palette";
import "ffcode-ht/plugins/propertypane";
// import "ffcode-ht/plugins/xeditinteractor";
import "ffcode-ht/plugins/dashflow";
import "ffcode-ht/plugins/flow";
export default ht;
